version: 2.1

orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build-and-deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - run:
          name: installing frontend
          command: |
            npm run frontend-install

      - run:
          name: building frontend
          command: |
            npm run frontend-build

      - run:
          name: deploying frontend
          command: |
            npm run frontend-deploy
      - run:
          name: installing backend
          command: |
            npm run backend-install

      - run:
          name: building backend
          command: |
            npm run backend-build

      - run:
          name: installing eb
          command: |
            npm run eb-install

      - run:
          name: deploying-backend
          command: |
            npm run backend-deploy

workflows:
  build-and-deploy:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - main
